spring:
  datasource:
    command:
      jdbc-url: jdbc:postgresql://pgdb:5432/reservation_service_command
      username: admin
      password: admin
      driver-class-name: org.postgresql.Driver

    query:
      jdbc-url: jdbc:postgresql://pgdb:5432/reservation_service_query
      username: admin
      password: admin
      driver-class-name: org.postgresql.Driver

  jpa:
    command:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          format_sql: true

    query:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  flyway:
    enabled: false
    command:
      locations: classpath:db/migration-command
    query:
      locations: classpath:db/migration-query
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
